### ISSUE TITLE
Redo the BMMC figures

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/DAMethods2016#3]
We should have used a slightly larger radius for the BMMC analysis. For some reason, the default radius gets us about 5 cells a hypersphere, which is not enough for differential testing. It seems that the intensities are quite highly variable across this population of cells - too diverse a mixture, perhaps? - so that even with more cells than the MEF reprogramming data set, the cells per hypersphere are lower.

A value of 0.55 seems appropriate, based on some diagnostic plots. This gets us to a median count of ~15 for each hypersphere, which should be good enough for analysis. Doing so identifies B cells as responding to IL-10 with increased pSTAT3, which is expected.

**Comment by jcmarioni** [comment]
Ok. This seems reasonable but not critical right? The filtering argument you will have to explain to me. 

Overall there is nothing too substantial here right?

John

**Comment by LTLA** [comment]
It's fine. In fact, it doesn't even need to be changed - while the current analysis is suboptimal, it's still pretty good, so I don't think anyone will notice. It's primarily for my own peace of mind.

**Comment by LTLA** [comment]
Done, updated BMMC analysis is now SF16-17.
